# Work in progress

version: "3.7"

services:
    redcoat_server:
        depends_on:
            - redcoat_db
        build:
            context: .
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.redcoat_server.rule=Host(`redcoat.localhost`)"
            #- "traefik.http.routers.redcoat_server.rule=Host(`localhost`)"
            #- "traefik.http.routers.redcoat_server.rule=Path(`/redcoat`)"
            - "traefik.http.routers.redcoat_server.entrypoints=web"
            - "traefik.docker.network=nlp-tlp-demos_traefiknet"
            - "traefik.http.services.redcoat_server.loadbalancer.server.port=80"
        networks:
            - redcoat
            - nlp-tlp-demos_traefiknet
    redcoat_db:
        image: mongo
        volumes:
            - nlpdata:/data/db
        ports:
            - "27017:27017"
        networks:
            - redcoat

    whoamiv2:
        image: "traefik/whoami"
        container_name: "simple-service-v2"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoamiv2.rule=Host(`127.0.0.1`)"
            - "traefik.http.routers.whoamiv2.rule=Path(`/whoamiv2`)"
            - "traefik.http.routers.whoamiv2.entrypoints=web"
            - "traefik.docker.network=nlp-tlp-demos_traefiknet"
        networks:
            - nlp-tlp-demos_traefiknet

networks:
    redcoat:
    nlp-tlp-demos_traefiknet:
        external: true
volumes:
    nlpdata:
